# -*- coding: utf-8 -*-
"""아모레워드클라우드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZUOp5Fqkgk5hBv3Nis01hwX_xp10xCF
"""

import pandas as pd

df1 = pd.read_excel('아모레퍼시픽_지속가능경영_뉴스데이터.xlsx')
df1.head()

df2 = pd.read_excel('아모레퍼시픽_esg_데이터.xlsx')
df2.head()

df = pd.concat([df1, df2])
df.head()

df = df.astype('str')
df['키워드'] = df['키워드'].str.replace(pat=r'(아모레퍼시픽|지속|가능|경영|ESG|기업|브랜드)', repl='', regex=True)
df['키워드']

!pip install konlpy

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=3000)

tdm = cv.fit_transform(df.키워드)

word_count_tf = pd.DataFrame({'단어':cv.get_feature_names_out(), '빈도': tdm.sum(axis=0).flat})
word_count_tf =word_count_tf.sort_values('빈도', ascending=False)
word_count_tf

word_count_tf.to_excel('amore_news_word_count.xlsx')

df = pd.read_excel('amore_news_word_count.xlsx')

df = df.dropna()
df.head(5)

from wordcloud import WordCloud

font_path = '/content/Arita4.0_M.otf'
wc = WordCloud(background_color='white', max_words=100, width=500, height=500, font_path=font_path)

count_dic = dict(zip(df['단어'], df['빈도']))
count_dic

cloud = wc.fit_words(count_dic)
cloud.to_image()

from sklearn.feature_extraction.text import TfidfTransformer
trans = TfidfTransformer()
dtm2 = trans.fit_transform(tdm)
df2 = pd.DataFrame({'단어':cv.get_feature_names_out(), 'tf-idf':dtm2.sum(axis=0).flat})
df2 = df2.sort_values('tf-idf', ascending=False)
df2 = df2.reset_index(drop=True)
df2.index = df2.index + 1
df2.to_excel(f'tf-idf.xlsx')

count_dic2 = dict(zip(df2['단어'], df2['tf-idf']))
cloud2 = wc.fit_words(count_dic2)
cloud2.to_image()