# -*- coding: utf-8 -*-
"""아모레LDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_yu_kR6WSHNtqaciUKMzHbZbZzGz0V0u
"""

import gensim.corpora as corpora
import gensim
from gensim.models.ldamodel import LdaModel
import matplotlib.pyplot as plt

import pandas as pd
df1 = pd.read_excel('/content/아모레퍼시픽_지속가능경영_뉴스데이터.xlsx')
df2 = pd.read_excel('/content/아모레퍼시픽_esg_데이터.xlsx')
data = pd.concat([df1, df2])
data.tail()

data = data.astype('str')
data['키워드'] = data['키워드'].str.replace(pat=r'(아모레퍼시픽|지속|가능|경영|ESG|기업|브랜드)', repl='', regex=True)
data['키워드']

token = [keywords.split(',') for keywords in data['키워드']]

id2word = corpora.Dictionary(token)
texts = token
corpus = [id2word.doc2bow(text) for text in texts]

import numpy as np
perplexity_values = []

for i in range(3, 10): #토픽수 3에서 9까지
  lda_model = gensim.models.ldamodel.LdaModel(corpus, num_topics=i, id2word=id2word)
  perplexity = np.exp2(-lda_model.log_perplexity(corpus))
  perplexity_values.append(perplexity)

x=range(3,10)
plt.plot(x, perplexity_values)
plt.xlabel('number of topics')
plt.ylabel('preplexity score')
plt.show()

from gensim.models import coherencemodel
from gensim.models import CoherenceModel
coherence_values = []

for i in range(3, 10): #토픽수 3에서 9까지
  ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics=i, id2word=id2word)
  coherence_model_lda = CoherenceModel(model=ldamodel, texts=token, dictionary=id2word, topn=10)
  coherence_lda = coherence_model_lda.get_coherence()
  coherence_values.append(coherence_lda)

x=range(3,10)
plt.plot(x, coherence_values)
plt.xlabel('number of topics')
plt.ylabel('coherence score')
plt.show() #토픽수 3로

#적정토픽에 해당되는 단어 찾기
from gensim import corpora, models, similarities
model = LdaModel(corpus=corpus, num_topics=3, id2word=id2word, passes=15)
topics = model.print_topics(num_words=11)
topics

!pip install pyLDAvis

!pip uninstall pandas

!pip install pandas==1.5.3

import pyLDAvis
import pyLDAvis.gensim_models

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim_models.prepare(model, corpus, id2word)
vis